<div class="row padded">
	  <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
		<div class="block1"><br /></div>
	  </div>
	  <div class="col-lg-8 col-md-6 col-sm-12 col-xs-12">
		<div class="block2">
			<h2>Список отзывов:</h2> <b>Присоединяйтесь,</b> 
			<a href="<?=$app['urlgen']->url(); ?>web/form">Оставьте ваш отзыв!</a>
			<br /><br />
			<div id="reviews">
			<?php if ( $comments ): ?>
				<?php foreach ( $comments as $comment ): ?>
					<div>
						<?php 
						echo 'Автор: <b>'.$comment['comment_username'].'</b>';// (IP: '.$comment['comment_userip'].') ';
						echo  '   Опубликовано: '.$comment['created_at'].'<br />'; ?>Отзыв: <a href="<?=$app['urlgen']->url(); ?>web/comment/<?=$comment['comment_id']; ?>"><?= $comment['comment']?></a>&nbsp;&nbsp;	&nbsp;	

						 <?php $IP = $_SERVER['REMOTE_ADDR']; ?>
						 <button type="button" value="<?php echo $comment['likes']?>" class="glyphicon glyphicon-thumbs-up btn btn-info" class='button_like' id='<?php echo 'linkeBtn'.$comment['comment_id']; ?>' data-commentid="<?= $comment['comment_id']?>" data-ip="<?= $IP ?>"><?= $comment['likes']?></button>						 
						 <hr />						 
					</div>
				<?php endforeach ?>

			<?php else: ?>
				Ничего не найдено
			<?php endif ?>
			</div>
		</div>
	  </div>
	  <div class="col-lg-2 col-md-4 col-sm-12 col-xs-12">
		<div class="block3">
			<div class="btn-group center">
				<br /><br />
				<button class="btn btn-info">Сортировка</button>
				<button class="btn dropdown-toggle" data-toggle="dropdown">
					<span class="caret"></span>
				</button>
				<ul class="dropdown-menu">
					<li><a tabindex="-1" href="<?=$app['urlgen']->url(); ?>web/comments/2/0">По дате (по убыванию)</a></li>
					<li><a tabindex="-1" href="<?=$app['urlgen']->url(); ?>web/comments/1/0">По дате (по возрастанию)</a></li>
					<li><a tabindex="-1" href="<?=$app['urlgen']->url(); ?>web/comments/0/2">По кол-ву лайков (по убыванию)</a></li>
					<li><a tabindex="-1" href="<?=$app['urlgen']->url(); ?>web/comments/0/1">По кол-ву лайков (по возрастанию)</a></li>
				</ul>
			</div>
			<br /><br /><br /><span id="status"></span>
		</div>
	  </div>                    
</div>
<?php $pathweb = __DIR__ . '/../../web'; ?>
<script src='<?=$app['urlgen']->url(); ?>/web/JS/flike.js'></script>
<script>flike();</script>
