
	<div class="row padded">
		  <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
			<div class="block1"><br />Сайдбар</div>
		  </div>
		  <div class="col-lg-8 col-md-6 col-md-offset-1 col-sm-12 col-xs-12">
			<div class="block2">
				<h2>Ваш отзыв:</h2> 
				<?php echo $form ?>	
			</div>
		  </div>
		  <div class="col-lg-2 col-md-3 col-sm-12 col-xs-12">
			<div class="block3">
				<a class="btn btn-lg btn-default" href="<?=$app['url_generator']->generate('reviews', array('sort1' => 0, 'sort2' => 0)); 
						?>" role="button">Список отзывов</a>
			</div>
		  </div>                    
	</div>
