	<div class="row padded">
		  <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
			<div class="block1"><br />Сайдбар</div>
		  </div>
		  <div class="col-lg-8 col-md-6 col-md-offset-1 col-sm-12 col-xs-12">
			<div class="block2"><br /><br />
				<h2>Отзыв:</h2><br />
				<div id="reviews">
					<?php if ( $review ): ?>
					<div>
						<?php 
						echo 'Автор: <b>'.$review['author'].'</b><br />';
						echo  'Опубликовано: '.$review['date'].'<br /></b>';
						echo ' Отзыв: '.$review['content'].'<br /></b>';
						$IP = $_SERVER['REMOTE_ADDR']; 
						?>
						
						<button type="button" value="<?php echo $review['likes']?>" class="glyphicon glyphicon-thumbs-up btn btn-info" class='button_like' id='<?php echo 'linkeBtn'.$review['id']; ?>' data-reviewid="<?= $review['id']?>" data-ip="<?= $IP ?>"><?= $review['likes']?></button>
						<hr />
						<a class="btn btn-lg btn-default" href="<?php echo $app['url_generator']->generate('form'); $i=0; ?>" role="button">Оставьте ваш отзыв!</a>
						
					</div>

					<?php else: ?>
						Отзыв не найден
					<?php endif ?>
				</div>
			</div>
		  </div>
		  <div class="col-lg-2 col-md-3 col-sm-12 col-xs-12">
			<div class="block3">				
				<a class="btn btn-lg btn-success" href="<?php 
						echo $app['url_generator']->generate('reviews', array('sort1' => 0, 'sort2' => 0)); 
						?>" role="button">Список отзывов</a>
				<br /><br /><br /><span id="status"></span>
			</div>
		  </div>                    
	</div>
<script src='../web/JS/flike.js'></script>
<script>flike();</script>
