<div class="row padded">
	  <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
		<div class="block1"><br /></div>
	  </div>
	  <div class="col-lg-8 col-md-6 col-sm-12 col-xs-12">
		<div class="block2">
			<h2>Список отзывов:</h2> <b>Присоединяйтесь,</b> 
			<a href="<?=$app['urlgen']->url(); ?>form">Оставьте ваш отзыв!</a>
			<br /><br />
			<div id="reviews">
			<?php if ( $reviews ): ?>
				<?php foreach ( $reviews as $review ): ?>
					<div>
						<?php 
						echo 'Автор: <b>'.$review['author'].'</b>';// (IP: '.$review['authorIP'].') ';
						echo  '   Опубликовано: '.$review['date'].'<br />'; ?>Отзыв: <a href="<?=$app['urlgen']->url(); ?>review/<?=$review['id']; ?>"><?= $review['content']?></a>&nbsp;&nbsp;	&nbsp;	

						 <?php $IP = $_SERVER['REMOTE_ADDR']; ?>
						 <button type="button" value="<?php echo $review['likes']?>" class="glyphicon glyphicon-thumbs-up btn btn-info" class='button_like' id='<?php echo 'linkeBtn'.$review['id']; ?>' data-reviewid="<?= $review['id']?>" data-ip="<?= $IP ?>"><?= $review['likes']?></button>						 
						 <hr />						 
					</div>
				<?php endforeach ?>

			<?php else: ?>
				Ничего не найдено
			<?php endif ?>
			</div>
		</div>
	  </div>
	  <div class="col-lg-2 col-md-4 col-sm-12 col-xs-12">
		<div class="block3">
			<div class="btn-group center">
				<br /><br />
				<button class="btn btn-info">Сортировка</button>
				<button class="btn dropdown-toggle" data-toggle="dropdown">
					<span class="caret"></span>
				</button>
				<ul class="dropdown-menu">
					<li><a tabindex="-1" href="<?=$app['urlgen']->url(); ?>reviews/2/0">По дате (по убыванию)</a></li>
					<li><a tabindex="-1" href="<?=$app['urlgen']->url(); ?>reviews/1/0">По дате (по возрастанию)</a></li>
					<li><a tabindex="-1" href="<?=$app['urlgen']->url(); ?>reviews/0/2">По кол-ву лайков (по убыванию)</a></li>
					<li><a tabindex="-1" href="<?=$app['urlgen']->url(); ?>reviews/0/1">По кол-ву лайков (по возрастанию)</a></li>
				</ul>
			</div>
			<br /><br /><br /><span id="status"></span>
		</div>
	  </div>                    
</div>
<?php $pathweb = __DIR__ . '/../../web'; ?>
<script src='<?=$app['urlgen']->url(); ?>/web/JS/flike.js'></script>
<script>flike();</script>
